import type { ReactNode } from "react";
import { BookOpen, Coins, HelpCircle, LockKeyhole, ReceiptText, Scale } from "lucide-react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { useSeo } from "@/lib/seo";

const updated = "September 4, 2026";

function SupportContact() {
  const supportEmail = String(import.meta.env.VITE_STORYHOLD_SUPPORT_EMAIL || "").trim();
  return supportEmail
    ? <a href={`mailto:${supportEmail}`} className="font-semibold text-primary hover:underline">{supportEmail}</a>
    : <Link href="/help" className="font-semibold text-primary hover:underline">Storyhold Help</Link>;
}

function LegalPage({ eyebrow, title, description, icon, children }: { eyebrow: string; title: string; description: string; icon: ReactNode; children: ReactNode }) {
  return <main className="mx-auto w-full max-w-4xl px-4 py-12 sm:px-6 sm:py-16 lg:px-8"><div className="flex items-start gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl border border-primary/25 bg-primary/10 text-primary">{icon}</span><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">{eyebrow}</p><h1 className="mt-2 font-serif text-4xl font-bold sm:text-5xl">{title}</h1><p className="mt-3 max-w-2xl text-base leading-7 text-muted-foreground">{description}</p><p className="mt-2 text-xs text-muted-foreground">Last updated {updated}</p></div></div><div className="mt-9 space-y-5">{children}</div></main>;
}

function Section({ title, children }: { title: string; children: ReactNode }) {
  return <Card className="rounded-3xl border-white/8 bg-white/[0.025] p-6 sm:p-7"><h2 className="font-serif text-2xl font-bold">{title}</h2><div className="mt-3 space-y-3 text-sm leading-7 text-muted-foreground">{children}</div></Card>;
}

export function StoryholdTerms() {
  useSeo({ title: "Terms of Use", description: "Storyhold terms of use.", canonicalPath: "/terms" });
  return <LegalPage eyebrow="Storyhold policies" title="Terms of Use" description="The ground rules for creating worlds, importing writing, and playing through Storyhold." icon={<Scale className="h-5 w-5" />}>
    <Section title="Your account and content"><p>You must provide accurate account information and keep your sign-in secure. You retain ownership of manuscripts, notes, characters, worlds, and other material you provide. You grant Storyhold only the limited permission needed to store, process, retrieve, and generate responses from that material for the service you request.</p><p>Do not upload material you lack the right to use. References to existing fictional universes remain subject to their owners' rights; Storyhold does not grant a commercial license to third-party intellectual property.</p></Section>
    <Section title="Canon Intake and imported sources"><p>Canon Intake is a paid digital processing service that extracts, indexes, classifies, and organizes eligible source material into a Storyhold world. One world intake can contain up to 250,000 cumulative narrative words across any number of files. Reference-only material is governed by its displayed reference policy and does not silently become story canon.</p><p>Storyhold determines the exact extractable word count after files are staged. An intake over 150,000 words requires more than 250 credits. Before paid reading begins, Storyhold verifies and reserves the complete required credit balance. If the balance is insufficient, the files remain saved, the reading does not begin, and no intake credits are consumed.</p><p>Duplicate files and completed stages are not charged again. A changed source may require new processing. Closing the page or losing a connection does not create a second charge; supported work resumes from saved checkpoints. See the <Link href="/credit-terms" className="font-semibold text-primary hover:underline">Credits and Intake Policy</Link>.</p></Section>
    <Section title="AI storytelling and canon"><p>Model-assisted output can be mistaken, inconsistent, or incomplete. Storyhold uses source citations, durable identities, owner constraints, and verification passes to reduce those errors, but it cannot promise perfect interpretation. Customer corrections and confirmed canon take priority over machine proposals.</p><p>Premium source verification is optional after local Canon Intake and consumes additional credits. In campaigns, consequences and locked starting state are governed by the selected play mode, including any separately priced reroll or branch options shown before use.</p></Section>
    <Section title="Content and adult mode"><p>You must be at least 18 to enable adult mode. Adult mode is optional and off by default. Content involving sexual exploitation of minors, instructions for real-world abuse, or other unlawful use is prohibited. Violence, horror, sexuality, and other mature fictional themes remain subject to the rules of the connected model provider and applicable law.</p></Section>
    <Section title="Credits, delivery, and refunds"><p>Credits are non-transferable Storyhold usage units and are not cash or a statement of Storyhold's underlying provider expense. Credit reservations temporarily reduce the spendable balance and settle against the work actually performed. Premium model work, gameplay, Canon Intake, rerolls, branches, and other features may use different credit schedules.</p><p>Completed digital processing is generally final once its output has been delivered to the account, except where required by law or covered by the <Link href="/refunds" className="font-semibold text-primary hover:underline">Refund and Technical Failure Policy</Link>. Failed intake reservations are released. Verified model work may still be metered when a response cannot safely be added to canon; Storyhold does not silently send that request a second time. Taxes, package contents, and any subscription terms are shown at checkout.</p></Section>
    <Section title="Acceptable use, suspension, and changes"><p>Do not attack the service, evade account or intake limits, access another person's Hold, manipulate credits, or use Storyhold for unlawful activity. We may suspend abusive use to protect customers, payment systems, and canonical data.</p><p>Material changes are dated and presented for renewed acceptance when appropriate. Questions may be sent through <SupportContact />.</p></Section>
  </LegalPage>;
}

export function StoryholdCreditTerms() {
  useSeo({ title: "Credits and Canon Intake", description: "How Storyhold credits, intake limits, reservations, and delivery work.", canonicalPath: "/credit-terms" });
  return <LegalPage eyebrow="Storyhold policies" title="Credits and Canon Intake" description="The customer-facing rules for paid world reading and Storyhold usage credits." icon={<Coins className="h-5 w-5" />}>
    <Section title="Cumulative world pricing"><p>Canon Intake is priced from the cumulative eligible word count of the world, not the number of files. One 150,000-word manuscript and eight files totaling 150,000 words receive the same world-intake price. The current schedule begins with a 100-credit world setup component and adds one credit per started 1,000 words. At 150,000 words, the complete local intake is 250 credits.</p><p>Later additions pay only the difference between the completed cumulative world price and the new cumulative price. Exact duplicates and already completed stages are not charged again. Meaningfully changed passages may require additional processing.</p></Section>
    <Section title="Word limit and large-intake warning"><p>One world Canon Intake accepts up to 250,000 cumulative eligible words. Storyhold warns when an intake exceeds 150,000 words because it will require more than 250 credits. Material exceeding the limit is not admitted into the paid intake and is not charged.</p><p>The limit applies across the world documents selected for intake, not separately to each uploaded file. Reference-only sources are identified and handled separately.</p></Section>
    <Section title="Full-balance reservation"><p>Files are staged and counted before paid reading begins. Storyhold then checks and reserves the full required balance. If the account cannot cover the complete intake, processing does not begin. Staged files remain available so the customer can add credits and resume without uploading them again.</p><p>A reservation is a temporary hold, not completed usage. The held amount is settled only after the local intake is saved and available in the customer's world. A technical failure releases the reservation or leaves recoverable work attached to the same request so it cannot be charged twice.</p></Section>
    <Section title="Premium and gameplay credits"><p>Premium AI verification is a separate, optional step after local Canon Intake. It uses credits according to the connected model and completed workload. For metered premium work, Storyhold may hold an estimated amount while processing. Unused held credits return automatically after settlement; if actual usage is higher, additional available credits may be used. If the balance cannot cover the difference, the completed work remains saved until the account is topped up and can finish without repeating the model request. Gameplay, dossier reviews, rerolls, branches, and other choices use the credit policy displayed or described for that feature.</p><p>Credits represent access to Storyhold products and processing. They are not redeemable for cash and do not represent a pass-through receipt for AI-provider expenses.</p></Section>
    <Section title="Questions or incorrect usage"><p>If a balance appears incorrect, stop retrying the same action and contact <SupportContact /> with the world name and approximate time. Storyhold retains reservation, settlement, delivery, and access records so duplicate or failed usage can be investigated.</p></Section>
  </LegalPage>;
}

export function StoryholdRefunds() {
  useSeo({ title: "Refund and Technical Failure Policy", description: "Storyhold refund, failed intake, duplicate charge, and service-delivery policy.", canonicalPath: "/refunds" });
  return <LegalPage eyebrow="Storyhold policies" title="Refund and Technical Failure Policy" description="What happens when paid digital work completes, pauses, fails, or appears more than once." icon={<ReceiptText className="h-5 w-5" />}>
    <Section title="Canon Intake does not charge a partial reading"><p>Storyhold reserves the full required balance before Canon Intake begins and settles it only after the local world intake is saved. If there are not enough credits, processing does not begin and no intake credits are consumed.</p><p>If Storyhold encounters an unrecoverable technical failure before delivery, the reservation is released. Recoverable work remains tied to the original request and resumes without a second intake charge.</p></Section>
    <Section title="Completed digital work"><p>Credits used for completed Canon Intake, premium verification, generated gameplay, dossier reviews, rerolls, branches, or other delivered digital processing are generally final once the result is available to the account. Dissatisfaction with a creative outcome does not by itself make completed compute unused, although author controls and separately priced alternatives may be available.</p><p>This policy does not limit refunds, cancellations, or other remedies required by applicable law.</p></Section>
    <Section title="Metered work that pauses"><p>For metered model work, the amount held before a request is an estimate. Storyhold automatically returns any unused portion. If the measured work costs more, Storyhold uses additional available credits; if the balance is insufficient, it preserves the completed response and original hold for top-up rather than calling the model again.</p><p>When Storyhold can verify that a provider performed billable work but cannot safely deliver its response into canon, measured credits may still be used. An outcome that cannot be verified remains paused for support review rather than being guessed, refunded, or automatically repeated.</p></Section>
    <Section title="Duplicate, incorrect, or unauthorized activity"><p>Storyhold will investigate credible reports of duplicate settlement, an incorrect balance adjustment, failure to deliver the paid service, or unauthorized account/payment activity. Contact <SupportContact /> promptly and include the account email, world name, approximate time, and the transaction or receipt identifier if available.</p><p>Do not provide passwords, full card numbers, or model-provider keys. Payment disputes are handled using the checkout receipt, credit ledger, intake logs, delivery status, and account-access records.</p></Section>
    <Section title="Unused purchased credits"><p>Eligibility for a refund of unused purchased credits follows the terms displayed at checkout and applicable law. Promotional, complimentary, or already consumed credits are not refundable for cash unless the checkout terms or applicable law require otherwise.</p></Section>
  </LegalPage>;
}

export function StoryholdPrivacy() {
  useSeo({ title: "Privacy", description: "How Storyhold handles accounts, manuscripts, worlds, and play data.", canonicalPath: "/privacy" });
  return <LegalPage eyebrow="Storyhold policies" title="Privacy" description="What the Hold stores, why it stores it, and how private world records stay separated." icon={<LockKeyhole className="h-5 w-5" />}>
    <Section title="What Storyhold stores"><p>Storyhold stores account details, credit balance and usage records, uploaded files, extracted source text, world entities, character dossiers, campaign events, messages, preferences, and the compact memories needed to continue a story. Canonical player, world, campaign, character, and source IDs keep one customer's records from being retrieved into another customer's game.</p></Section>
    <Section title="How your material is used"><p>Your material is used to provide the features you request: importing and indexing sources, building grounded world records, retrieving relevant context, generating scenes, checking continuity, and maintaining campaign state. Connected AI providers receive only the context needed for the current task, subject to their configured data terms.</p><p>Uploaded prose, private feedback notes, and private canon are not placed into cross-game learning. Anonymous pattern learning is separate, opt-in, and limited to de-identified structural outcomes and rating counts; it cannot silently rewrite a player's world.</p></Section>
    <Section title="Browser and server processing"><p>Some supported intake checks can run inside the customer's browser. Passages handled exclusively by a browser-local model remain on that device for that step, while resulting evidence and approved records may be saved to the account. Server-side extraction, indexing, retrieval, and connected premium providers process the material needed for the requested feature.</p></Section>
    <Section title="Retention, deletion, and export"><p>World and campaign records remain with the account so long stories can continue. Deleting a world removes its service records and stored uploads subject to operational backups, legal retention, fraud prevention, and payment records that must be preserved. Account export and deletion controls will identify any records that cannot be removed immediately.</p></Section>
    <Section title="Security and service providers"><p>Storyhold uses hashed passwords, server-side sessions, access checks, canonical scope checks, and private storage boundaries. Hosting, AI, storage, email, analytics, and payment providers may process the minimum data needed for their role once configured. A public launch privacy notice will identify material providers and regional rights before accepting payments.</p></Section>
  </LegalPage>;
}

export function StoryholdHelp() {
  useSeo({ title: "Help", description: "Help with Storyhold accounts, worlds, imports, credits, and storyteller connections.", canonicalPath: "/help" });
  const supportEmail = String(import.meta.env.VITE_STORYHOLD_SUPPORT_EMAIL || "").trim();
  return <LegalPage eyebrow="Help center" title="How can we help?" description="Quick answers for building a world, importing a manuscript, and keeping a campaign moving." icon={<HelpCircle className="h-5 w-5" />}>
    <Section title="My storyteller says it is offline"><p>Storyhold pauses instead of returning a canned response when no live model connection is available. Your worlds and Hold records remain intact. In a local or Replit build, the owner must configure at least one supported AI connection before live scenes and deeper source reading can run.</p></Section>
    <Section title="My import found the wrong kind of thing"><p>Open the world's Hold to reclassify a record across Storyhold categories, including people, places, groups, species, technology, vehicles, devices, and weapons. You can merge aliases and nicknames, undo a merge, assign connections, or mark a false find as do not pull.</p><Button asChild variant="outline" className="mt-2"><Link href="/profile/worlds"><BookOpen className="mr-2 h-4 w-4" /> Open my worlds</Link></Button></Section>
    <Section title="Credits changed more than I expected"><p>Credit use varies with reply length, reasoning, model route, and how much of a large world must be recalled. Storyhold shows only credits reserved, used, refunded, and remaining—not underlying provider bills.</p></Section>
    <Section title="Contact support">{supportEmail ? <><p>Send account and technical questions to the Storyhold support team. Do not include passwords or AI provider keys.</p><Button asChild><a href={`mailto:${supportEmail}`}>Email {supportEmail}</a></Button></> : <p>This development build has no public support address configured. Set <span className="font-mono text-foreground/80">VITE_STORYHOLD_SUPPORT_EMAIL</span> before public launch to enable the support link.</p>}</Section>
  </LegalPage>;
}
